version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: ghost
            MYSQL_USER: ghostuser
            MYSQL_PASSWORD: ocrpassword

    ghost:
        depends_on:
            - db
        build: ./DockerFile
        ports:
            - "2365:80"
        restart: always
        environment:
            NODE_ENV: production
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ghostuser
            WORDPRESS_DB_PASSWORD: ocrpassword
            WORDPRESS_DB_NAME: ghost

volumes:
    db_data: {}
